### ISSUE TITLE
Add a feature for component types or classifiers of some kind

### ISSUE THREAD

**Issue by winjer** [isotoma/threat-model-manager#1]
We want to be able to define some kind of classifications of nodes and edges, so we can then define threats against those classifiers.

Candidate yaml:

```
classes:
    public-api-gateway:
        label: Public API Gateway
        threats:
            - type: unauthorised access
              threat: bypass authorizer

nodes:
    my-api:
        label: My API
        class: public-api-gateway
```

would produce a node with a label like:

           My API
    [Public API Gateway]

and the output threats html would include a section for the public api gateway class initially, and would refer to it in the node table somehow.
